export const CHART_DIMENSIONS = {
  provider: "Provider",
  model: "Model",
  channel_name: "Channel",
  platform: "Platform",
  cost_mode: "Cost mode",
  machine_identity: "Machine",
  gateway_profile: "Gateway",
  status: "Status",
  error_code: "Error code",
  call_source: "Source",
  platform_user_id: "User ID",
  platform_user_display_name: "User",
  session_key: "Session key",
  session_id: "Session ID",
  run_id: "Run ID",
  turn_id: "Turn ID",
  request_id: "Request ID",
  provider_request_id: "Provider request ID",
  agent_id: "Agent ID",
  agent_name: "Agent",
  runtime_id: "Runtime",
} as const;

export const CHART_METRICS = {
  events: "Events",
  input_tokens: "Input tokens",
  output_tokens: "Output tokens",
  total_tokens: "Total tokens",
  cache_read_tokens: "Cache read tokens",
  cache_write_tokens: "Cache write tokens",
  reasoning_tokens: "Reasoning tokens",
  estimated_cost_usd: "Estimated cost (USD)",
  input_cost_usd: "Input cost (USD)",
  output_cost_usd: "Output cost (USD)",
  cache_cost_usd: "Cache cost (USD)",
  duration_ms: "Duration (ms)",
  time_to_first_token_ms: "TTFT (ms)",
  retry_count: "Retries",
  tool_call_count: "Tool calls",
  error_events: "Error events",
  success_events: "Success events",
} as const;

export type ChartDimension = keyof typeof CHART_DIMENSIONS;
export type ChartMetric = keyof typeof CHART_METRICS;

export const USAGE_EVENT_COLUMNS = [
  "id",
  "created_at",
  "started_at",
  "ended_at",
  "duration_ms",
  "time_to_first_token_ms",
  "gateway_profile",
  "agent_id",
  "agent_name",
  "runtime_id",
  "machine_identity",
  "platform",
  "channel_name",
  "platform_user_id",
  "platform_user_display_name",
  "platform_tenant_id",
  "platform_conversation_id",
  "platform_message_id",
  "thread_id",
  "session_key",
  "session_id",
  "run_id",
  "turn_id",
  "request_id",
  "provider_request_id",
  "call_source",
  "provider",
  "model",
  "input_tokens",
  "output_tokens",
  "total_tokens",
  "cache_read_tokens",
  "cache_write_tokens",
  "reasoning_tokens",
  "estimated_cost_usd",
  "input_cost_usd",
  "output_cost_usd",
  "cache_cost_usd",
  "cost_mode",
  "context_tokens_before",
  "context_tokens_after",
  "context_window",
  "had_tool_calls",
  "tool_call_count",
  "tool_names_json",
  "status",
  "error_code",
  "error_message",
  "retry_count",
  "prompt_hash",
  "response_hash",
  "preview",
  "raw_usage_json",
  "metadata_json",
] as const;

export type UsageEventColumn = typeof USAGE_EVENT_COLUMNS[number];

export const DEFAULT_CHART_DIMENSIONS: ChartDimension[] = ["provider", "model", "channel_name"];
export const DEFAULT_CHART_METRICS: ChartMetric[] = ["total_tokens"];
